language: ruby
rvm:
  - 2.3
script:
  - gem install cfhighlander --prerelease
  - if [ "${TRAVIS_PULL_REQUEST}" != "false" ]; then cfndsl -u && cfhighlander cfcompile ; else cfndsl -u && cfhighlander cfcompile --validate; fi
